import type { NextPage } from "next";
import Head from "next/head";
import BillingSection from "../components/billing/BillingSection";
import SubscriptionCard from "../components/billing/card/SubscriptionCard";
import Button from "../components/buttons/Button";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full h-screen px-20 py-10 ">
        {/* Heading */}
        <div className="mb-10">
          <h1 className="text-[32px] font-bold">Billing</h1>
        </div>

        <div className="">
          <div className=" w-[90%]">
            <BillingSection title="Payment Method" />

            <div className="flex justify-between items-center w-[70%] mt-8">
              <div className="flex items-center gap-8">
                <div>
                  <Button>
                    <img src="/myvisa.png" alt="visa" />
                  </Button>
                </div>

                <div>
                  <h3 className="text-[16px] text-darkBlueColor font-medium">
                    Visa ending in 2255
                  </h3>
                </div>
              </div>

              {/* Remove Button */}
              <div>
                <Button>Remove</Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
