import type { NextPage } from "next";
import Head from "next/head";
import BillingSection from "../components/billing/BillingSection";
import SubscriptionCard from "../components/billing/card/SubscriptionCard";
import ReceiptTable from "../components/billing/receiptTable/ReceiptTable";
import Button from "../components/buttons/Button";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Camsol Code Interview</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full h-screen px-14 py-10 ">
        {/* Heading */}
        <div className="mb-10 ml-6">
          <h1 className="text-[32px] font-bold">Billing</h1>
        </div>

        {/* Receipt Section */}
        <div>
          <div className="w-full grid grid-cols-12  ">
            <div className="w-full    col-span-9">
              <div className="mb-14">
                <BillingSection title="Order History" />
              </div>

              <div className="w-[89%] ">
                <ReceiptTable />
              </div>
            </div>

            <div className="w-full col-span-3">
              <SubscriptionCard />
            </div>
          </div>

    {/* Bottom section of page */}
          <div className=" w-[90%] mt-9">
            <BillingSection title="Payment Method" />

            <div className="flex justify-between items-center w-[70%] mt-4 ml-6">
              <div className="flex items-center gap-8">
                <div>
                  <Button>
                    <img src="/myvisa.png" alt="visa" />
                  </Button>
                </div>

                <div>
                  <h3 className="text-[16px] text-darkBlueColor font-medium">
                    Visa ending in 2255
                  </h3>
                </div>
              </div>

              {/* Remove Button */}
              <div>
                <Button>Remove</Button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Home;
